[book]
authors = ["adisbladis"]
language = "en"
src = "src"
title = "uv2nix"

[preprocessor.cmdrun]
command = "mdbook-cmdrun"

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
renderer = ["html"]
git-repository-url = "https://github.com/pyproject-nix/uv2nix"
git-branch = "master"
open-on-text = """
<hr style="margin-top: 5em;" />
Found an issue? [Edit this page on GitHub.]
"""
